Docs - Fixed double quotes issue with feature-gates
Double quotes was giving error as below, may be need to update the code to accept the double quotes.

Error: invalid argument "\"GracefulNodeShutdown=true\"" for "--feature-gates" flag: invalid value of "GracefulNodeShutdown=true", err: strconv.ParseBool: parsing "true\"": invalid syntax